import {
  AirConditionerIcon,
  ArrowDownIcon,
  BellIcon,
  BicycleIcon,
  ChevronIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChevronCircleDownIcon,
  ChevronCircleLeftIcon,
  ChevronCircleRightIcon,
  ChevronCircleUpIcon,
  CheckCircleIcon,
  CheckedIcon,
  CircleIcon,
  CloseIcon,
  CrossIcon,
  DeleteIcon,
  DownloadIcon,
  EditIcon,
  ExclamationCircleIcon,
  FilePdfIcon,
  FlagIcon,
  FullScreenIcon,
  GroupIcon,
  ImageIcon,
  ListIcon,
  MapMarkerIcon,
  MenuBarsIcon,
  MicIcon,
  OctagonIcon,
  PaperPlaneIcon,
  PauseCircleIcon,
  PlayCircleIcon,
  PlusIcon,
  SaveIcon,
  SearchIcon,
  StarIcon,
  SquareIcon,
  SquareCloseIcon,
  TriangleIcon,
  UploadIcon,
  VerticalThreeDotsIcon,
  ThermometerIcon,
  SensorIcon,
  SmokeDetectorIcon,
  SirenIcon,
  DesktopIcon,
  MeetingRoomIcon,
  TelevisionIcon,
  ProjectorIcon,
  DeskIcon,
  CoffeeMachineIcon,
  MicrowaveIcon,
  OvenIcon,
  PumpIcon,
  BoilerIcon,
  DishwasherIcon,
  FreezerIcon,
  FridgeIcon,
  FuseBoxIcon,
  SprinkleIcon,
  WashingMachineIcon,
} from './components'

export const RawIcons = {
  airConditioner: AirConditionerIcon,
  arrowDown: ArrowDownIcon,
  bell: BellIcon,
  bicycle: BicycleIcon,
  chevron: ChevronIcon,
  chevronDown: ChevronDownIcon,
  chevronLeft: ChevronLeftIcon,
  chevronRight: ChevronRightIcon,
  chevronUp: ChevronUpIcon,
  chevronCircleDown: ChevronCircleDownIcon,
  chevronCircleLeft: ChevronCircleLeftIcon,
  chevronCircleRight: ChevronCircleRightIcon,
  chevronCircleUp: ChevronCircleUpIcon,
  checkCircle: CheckCircleIcon,
  checked: CheckedIcon,
  circle: CircleIcon,
  close: CloseIcon,
  cross: CrossIcon,
  delete: DeleteIcon,
  download: DownloadIcon,
  edit: EditIcon,
  exclamationCircle: ExclamationCircleIcon,
  filePdf: FilePdfIcon,
  flag: FlagIcon,
  fullScreen: FullScreenIcon,
  group: GroupIcon,
  image: ImageIcon,
  list: ListIcon,
  mapMarker: MapMarkerIcon,
  menuBars: MenuBarsIcon,
  mic: MicIcon,
  octagon: OctagonIcon,
  paperPlane: PaperPlaneIcon,
  pauseCircle: PauseCircleIcon,
  playCircle: PlayCircleIcon,
  plus: PlusIcon,
  save: SaveIcon,
  search: SearchIcon,
  star: StarIcon,
  square: SquareIcon,
  squareClose: SquareCloseIcon,
  triangle: TriangleIcon,
  upload: UploadIcon,
  verticalThreeDots: VerticalThreeDotsIcon,
  thermometer: ThermometerIcon,
  sensor: SensorIcon,
  smokeDetector: SmokeDetectorIcon,
  siren: SirenIcon,
  desktop: DesktopIcon,
  meetingRoom: MeetingRoomIcon,
  television: TelevisionIcon,
  projector: ProjectorIcon,
  desk: DeskIcon,
  coffeeMachine: CoffeeMachineIcon,
  microwave: MicrowaveIcon,
  oven: OvenIcon,
  pump: PumpIcon,
  boiler: BoilerIcon,
  dishwasher: DishwasherIcon,
  freezer: FreezerIcon,
  fridge: FridgeIcon,
  fuseBox: FuseBoxIcon,
  sprinkle: SprinkleIcon,
  washingMachine: WashingMachineIcon,
}
