import { COLOUR } from '../../theme/variables/colour'

export const MESSAGING = {
  audioAndVolumeProgressColour: COLOUR.info,
  audioControllersColour: COLOUR.primary,
  containerBackground: COLOUR.grey,
  dropableHeaderBackground: COLOUR.drykiss_lightBlue,
  forwardAndReplyIconsColour: COLOUR.blackText,
  hashtagColour: COLOUR.secondary,
  headerBackground: COLOUR.light,
  inputFontSize: '1rem',
  inputIconsColour: COLOUR.blackGrey,
  inpotIconsHoverColour: COLOUR.info,
  inputSectionBackground: COLOUR.light,
  linkColour: COLOUR.primary,
  maxInputHeight: '6rem',
  mentionColour: COLOUR.blackText,
  messageBorderColour: COLOUR.grey80,
  messageContentColour: COLOUR.black,
  messageFontSize: '1rem',
  messageIconColour: COLOUR.primary,
  messageReplyRextColour: COLOUR.blackText,
  messageTimeTextColour: COLOUR.primary,
  receivedMessageBackground: COLOUR.neutral,
  recorderRecordingStateColour: COLOUR.success,
  recorderLoadingStateColour: COLOUR.grey,
  scrollBarColour: COLOUR.watterBlue,
  scrollThumbColour: COLOUR.blackGrey,
  sentMessageBackground: COLOUR.neutral2
}
