/**
 * Hooks - Use Component Communication - Message Names
 */
export const MessageNames = {
  DetailsComponent: {
    SET_OPEN: 'TOGGLE_OPEN'
  },
  Messaging: {
    MESSAGING_ACTION: 'MESSAGING_ACTION'
  },
  TEST: 'TEST',
  UPDATE_CHART_DATA: 'UPDATE_CHART_DATA'
}

export const MessagingActions = {
  CLEAR_INPUT: 'CLEAR_INPUT',
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  EDIT_MESSAGE: 'EDIT_MESSAGE',
  HASHTAG_CLICKED: 'HASHTAG_CLICKED',
  MENTION_CLICKED: 'MENTION_CLICKED',
  NEW_MESSAGES: 'NEW_MESSAGES',
  RENEW_MESSAGES: 'RENEW_MESSAGES',
  REPLY_MESSAGE: 'REPLY_MESSAGE',
  SET_ATTACHMENTS_TO_NEW_MESSAGE: 'SET_ATTACHMENTS_TO_NEW_MESSAGE',
  SET_DOCUMENT_INFO: 'SET_DOCUMENT_INFO',
  SET_FULL_PREVIEW_FILES: 'SET_FULL_PREVIEW_FILES',
  SET_RECORDED_VOICE: 'SET_RECORDED_VOICE',
  STAR_MESSAGE: 'STAR_MESSAGE'
}
