/**
 * Hooks - Use Component Communication - Message Names
 */
export const MessageNames = {
  Messaging: {
    CLEAR_INPUT: 'CLEAR_INPUT',
    HASHTAG_CLICKED: 'HASHTAG_CLICKED',
    MENTION_CLICKED: 'MENTION_CLICKED',
    NEW_MESSAGES: 'NEW_MESSAGES',
    RENEW_MESSAGES: 'RENEW_MESSAGES',
    SET_ATTACHMENTS_TO_NEW_MESSAGE: 'SET_ATTACHMENTS_TO_NEW_MESSAGE'
  },
  TEST: 'TEST',
  UPDATE_CHART_DATA: 'UPDATE_CHART_DATA'
}
