/**
 * Components - Services - Component Communication - Message Actions
 */

const MessagingActions = {
  CLEAR_INPUT: 'CLEAR_INPUT',
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  EDIT_MESSAGE: 'EDIT_MESSAGE',
  HASHTAG_CLICKED: 'HASHTAG_CLICKED',
  MENTION_CLICKED: 'MENTION_CLICKED',
  NEW_MESSAGES: 'NEW_MESSAGES',
  IS_SENDING_MESSAGE: 'IS_SENDING_MESSAGE',
  RENEW_MESSAGES: 'RENEW_MESSAGES',
  REPLY_MESSAGE: 'REPLY_MESSAGE',
  SET_ATTACHMENTS_TO_NEW_MESSAGE: 'SET_ATTACHMENTS_TO_NEW_MESSAGE',
  SET_DOCUMENT_INFO: 'SET_DOCUMENT_INFO',
  SET_FULL_PREVIEW_FILES: 'SET_FULL_PREVIEW_FILES',
  SET_RECORDED_VOICE: 'SET_RECORDED_VOICE',
  STAR_MESSAGE: 'STAR_MESSAGE'
}

export default MessagingActions
