/**
 * Hooks - Use Component Communication - Message Names
 */
export const MessageNames = {
  TEST: 'TEST',
  UPDATE_CHART_DATA: 'UPDATE_CHART_DATA',
  Messaging: {
    NEW_MESSAGES: 'NEW_MESSAGES',
    SET_ATTACHMENTS_TO_NEW_MESSAGE: 'SET_ATTACHMENTS_TO_NEW_MESSAGE',
    HASHTAG_CLICKED: 'HASHTAG_CLICKED',
    CLEAR_INPUT: 'CLEAR_INPUT',
    MENTION_CLICKED: 'MENTION_CLICKED'
  }
}
